repos:
  - repo: local
    hooks:
      - id: shexli
        name: shexli
        entry: make pack lint
        language: system
        pass_filenames: false
        always_run: true
        description: "Static analyzer for GNOME Shell extensions"
